### ISSUE TITLE
Schema/API Design comments Ash Mitchell

### ISSUE THREAD

**Issue by amitch35** [arnenoori/reciepts-webapp#3]
You had some great ideas with the schema design but there are a few things I want to mention:

1. Most endpoints share a path with another operation
I am not 100% sure if this is a problem but almost all of your endpoints share a path with another one (i.e. you use `/user/{user_id}` for all of: making, changing, and deleting a user). This is fine if you are calling the site from the docs and maybe an application program but I am just imagining what would happen if you were to put these paths directly into the browser. For example, neither getting or deleting a user require a json input, so if I just put `/user/{user_id}` into my browser is it going to create a user or delete one? I would suggest changing your paths to make them all unique in some way.

2. Consider making email part of primary key or at least constraining it to be unique
If you go on to use email and password in any form of authentication you will probably want email to be unique such that when you are validating passwords you don't end up checking against another user's password.

3. Users can change their email?
I understand why you made it possible for users to change their name but if email is used as a way to uniquely identify the user as their username (as suggested above) you might not want them changing their email all the time. I would suggest adding an unchangeable username attribute for users if you want users to be able to change their email. That way you can have people put in a username and password instead of an email when authenticating.

4. User password?
Your table schema has no place for passwords or anything related to them. Your README suggests that the service will have logins and a dashboard for users but your schema and account creation endpoint don't seem to account for passwords

5. `/user/{user_id}/transactions/` Also output transaction_id
I am imagining this endpoint would be used by users to see all the transaction they have in the system if they have forgotten them. It could be very useful but what if they want to edit or remove a transaction that they see on the list? Unless they happen to have their own personal list of transactions with their associated transaction_ids, they will have no way of knowing what the transaction_ids for all those transactions are and would have no way of changing them. You should list the transaction_id along with the merchant, description, and created_at.

6. `/user/{user_id}/purchases/` Also output purchase_id
For a similar reason as above, you probably want to be returning the information necessary to actually work with those purchases that someone asks for. You should list the purchase_id alongside the other details of the purchase.

7. `/user/{user_id}/transactions/` Probably don't need created_at to be listed
I am assuming that in many use cases for this service, the created_at field of the transactions is not going to match the actual time the transaction occurred in real life so the created_at field may be unnecessary when listing a user's transactions.

8. Purchases have warranty and return dates, but not a purchase date? 
I might suggest adding a purchase date to either the transactions or purchases table so that users have a way to track their purchases over time.

9. How are Receipts used by a user
I see that you have a table for receipts which you stated would be text which was converted from images of a receipt. There is no way however for a user to view or change the content of the receipt. Are you going to convert the receipt into a transaction and purchases automatically and then make those things available for the user to edit as needed?

10. Financial Goals
Your README and ER diagram mentions financial goals and planning. You don't have any tables related to financial goals listed in your schema and there are no endpoints to create, view, or alter a financial goal.

11. How are you tracking and evaluating budgets
If you only have information about the purchases the user is making, how are you going to do any budget tracking or suggestions? I would suggest maybe having a user input their monthly income and using the purchase dates or purchases to see if they are on track with their budget or something like that. Or if you prefer you could use the financial goals mentioned above somehow to track or suggest budget information as well.

12. ER diagram mismatch
Your ER diagram does not accurately depict the entities you have within your application. Purchases should probably be connected to a transaction entity which connects to users in order to accurately depict the way your tables are connected to each other.

**Comment by jackalnom** [comment]
Don't make email part of primary key, but I agree with putting a unique constraint on it. And I can tell you from experience, always let people change their usernames....
